// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: proto/vatz/plugin/v1/plugin.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ALERT_TYPE int32

const (
	ALERT_TYPE_DISCORD    ALERT_TYPE = 0
	ALERT_TYPE_PAGER_DUTY ALERT_TYPE = 1
	ALERT_TYPE_TELEGRAM   ALERT_TYPE = 3
)

// Enum value maps for ALERT_TYPE.
var (
	ALERT_TYPE_name = map[int32]string{
		0: "DISCORD",
		1: "PAGER_DUTY",
		3: "TELEGRAM",
	}
	ALERT_TYPE_value = map[string]int32{
		"DISCORD":    0,
		"PAGER_DUTY": 1,
		"TELEGRAM":   3,
	}
)

func (x ALERT_TYPE) Enum() *ALERT_TYPE {
	p := new(ALERT_TYPE)
	*p = x
	return p
}

func (x ALERT_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ALERT_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_vatz_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (ALERT_TYPE) Type() protoreflect.EnumType {
	return &file_proto_vatz_plugin_v1_plugin_proto_enumTypes[0]
}

func (x ALERT_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ALERT_TYPE.Descriptor instead.
func (ALERT_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_proto_vatz_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type STATE int32

const (
	STATE_NONE        STATE = 0
	STATE_PENDING     STATE = 1
	STATE_IN_PROGRESS STATE = 2
	STATE_SUCCESS     STATE = 3
	STATE_FAILURE     STATE = 4
	STATE_TIMEOUT     STATE = 5
)

// Enum value maps for STATE.
var (
	STATE_name = map[int32]string{
		0: "NONE",
		1: "PENDING",
		2: "IN_PROGRESS",
		3: "SUCCESS",
		4: "FAILURE",
		5: "TIMEOUT",
	}
	STATE_value = map[string]int32{
		"NONE":        0,
		"PENDING":     1,
		"IN_PROGRESS": 2,
		"SUCCESS":     3,
		"FAILURE":     4,
		"TIMEOUT":     5,
	}
)

func (x STATE) Enum() *STATE {
	p := new(STATE)
	*p = x
	return p
}

func (x STATE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (STATE) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_vatz_plugin_v1_plugin_proto_enumTypes[1].Descriptor()
}

func (STATE) Type() protoreflect.EnumType {
	return &file_proto_vatz_plugin_v1_plugin_proto_enumTypes[1]
}

func (x STATE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use STATE.Descriptor instead.
func (STATE) EnumDescriptor() ([]byte, []int) {
	return file_proto_vatz_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

type SEVERITY int32

const (
	SEVERITY_UNKNOWN  SEVERITY = 0
	SEVERITY_WARNING  SEVERITY = 1
	SEVERITY_ERROR    SEVERITY = 2
	SEVERITY_CRITICAL SEVERITY = 3
	SEVERITY_INFO     SEVERITY = 4
)

// Enum value maps for SEVERITY.
var (
	SEVERITY_name = map[int32]string{
		0: "UNKNOWN",
		1: "WARNING",
		2: "ERROR",
		3: "CRITICAL",
		4: "INFO",
	}
	SEVERITY_value = map[string]int32{
		"UNKNOWN":  0,
		"WARNING":  1,
		"ERROR":    2,
		"CRITICAL": 3,
		"INFO":     4,
	}
)

func (x SEVERITY) Enum() *SEVERITY {
	p := new(SEVERITY)
	*p = x
	return p
}

func (x SEVERITY) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SEVERITY) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_vatz_plugin_v1_plugin_proto_enumTypes[2].Descriptor()
}

func (SEVERITY) Type() protoreflect.EnumType {
	return &file_proto_vatz_plugin_v1_plugin_proto_enumTypes[2]
}

func (x SEVERITY) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SEVERITY.Descriptor instead.
func (SEVERITY) EnumDescriptor() ([]byte, []int) {
	return file_proto_vatz_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

type ExecuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//is_required: True
	ExecuteInfo *structpb.Struct `protobuf:"bytes,1,opt,name=execute_info,json=executeInfo,proto3" json:"execute_info,omitempty"`
	//is_required: True
	Options *structpb.Struct `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vatz_plugin_v1_plugin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vatz_plugin_v1_plugin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_vatz_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetExecuteInfo() *structpb.Struct {
	if x != nil {
		return x.ExecuteInfo
	}
	return nil
}

func (x *ExecuteRequest) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State   STATE  `protobuf:"varint,1,opt,name=state,proto3,enum=vatz.plugin.STATE" json:"state,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Deprecated: Do not use.
	AlertType    []ALERT_TYPE `protobuf:"varint,3,rep,packed,name=alert_type,json=alertType,proto3,enum=vatz.plugin.ALERT_TYPE" json:"alert_type,omitempty"`
	Severity     SEVERITY     `protobuf:"varint,4,opt,name=severity,proto3,enum=vatz.plugin.SEVERITY" json:"severity,omitempty"`
	ResourceType string       `protobuf:"bytes,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vatz_plugin_v1_plugin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vatz_plugin_v1_plugin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_vatz_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetState() STATE {
	if x != nil {
		return x.State
	}
	return STATE_NONE
}

func (x *ExecuteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Deprecated: Do not use.
func (x *ExecuteResponse) GetAlertType() []ALERT_TYPE {
	if x != nil {
		return x.AlertType
	}
	return nil
}

func (x *ExecuteResponse) GetSeverity() SEVERITY {
	if x != nil {
		return x.Severity
	}
	return SEVERITY_UNKNOWN
}

func (x *ExecuteResponse) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type CollectorVerifyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *structpb.Struct `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *CollectorVerifyInfo) Reset() {
	*x = CollectorVerifyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vatz_plugin_v1_plugin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectorVerifyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorVerifyInfo) ProtoMessage() {}

func (x *CollectorVerifyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vatz_plugin_v1_plugin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorVerifyInfo.ProtoReflect.Descriptor instead.
func (*CollectorVerifyInfo) Descriptor() ([]byte, []int) {
	return file_proto_vatz_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *CollectorVerifyInfo) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

type VerifyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerifyMsg string `protobuf:"bytes,1,opt,name=verify_msg,json=verifyMsg,proto3" json:"verify_msg,omitempty"`
}

func (x *VerifyInfo) Reset() {
	*x = VerifyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vatz_plugin_v1_plugin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyInfo) ProtoMessage() {}

func (x *VerifyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vatz_plugin_v1_plugin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyInfo.ProtoReflect.Descriptor instead.
func (*VerifyInfo) Descriptor() ([]byte, []int) {
	return file_proto_vatz_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyInfo) GetVerifyMsg() string {
	if x != nil {
		return x.VerifyMsg
	}
	return ""
}

var File_proto_vatz_plugin_v1_plugin_proto protoreflect.FileDescriptor

var file_proto_vatz_plugin_v1_plugin_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x61, 0x74, 0x7a, 0x2f, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x76, 0x61, 0x74, 0x7a, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7f, 0x0a, 0x0e, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a,
	0x0c, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0b, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x31, 0x0a, 0x07, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xe9, 0x01, 0x0a,
	0x0f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x28, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x76, 0x61, 0x74, 0x7a, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x76, 0x61, 0x74, 0x7a, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x41, 0x4c, 0x45, 0x52, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x42, 0x02, 0x18, 0x01, 0x52, 0x09, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x31, 0x0a, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x15, 0x2e, 0x76, 0x61, 0x74, 0x7a, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2e, 0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x52, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x48, 0x0a, 0x13, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x31, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x2b, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4d, 0x73, 0x67, 0x2a,
	0x37, 0x0a, 0x0a, 0x41, 0x4c, 0x45, 0x52, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0b, 0x0a,
	0x07, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x52, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x41,
	0x47, 0x45, 0x52, 0x5f, 0x44, 0x55, 0x54, 0x59, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x45,
	0x4c, 0x45, 0x47, 0x52, 0x41, 0x4d, 0x10, 0x03, 0x2a, 0x56, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50,
	0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x5f, 0x50,
	0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52,
	0x45, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x49, 0x4d, 0x45, 0x4f, 0x55, 0x54, 0x10, 0x05,
	0x2a, 0x47, 0x0a, 0x08, 0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x52,
	0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x02, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x52, 0x49, 0x54, 0x49, 0x43, 0x41, 0x4c, 0x10, 0x03, 0x12,
	0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x04, 0x32, 0x8d, 0x01, 0x0a, 0x06, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x12, 0x3b, 0x0a, 0x06, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x76, 0x61, 0x74, 0x7a, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x00, 0x12, 0x46, 0x0a, 0x07, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x76,
	0x61, 0x74, 0x7a, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x76, 0x61, 0x74, 0x7a,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_vatz_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_proto_vatz_plugin_v1_plugin_proto_rawDescData = file_proto_vatz_plugin_v1_plugin_proto_rawDesc
)

func file_proto_vatz_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_proto_vatz_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_proto_vatz_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_vatz_plugin_v1_plugin_proto_rawDescData)
	})
	return file_proto_vatz_plugin_v1_plugin_proto_rawDescData
}

var file_proto_vatz_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_vatz_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_vatz_plugin_v1_plugin_proto_goTypes = []interface{}{
	(ALERT_TYPE)(0),             // 0: vatz.plugin.ALERT_TYPE
	(STATE)(0),                  // 1: vatz.plugin.STATE
	(SEVERITY)(0),               // 2: vatz.plugin.SEVERITY
	(*ExecuteRequest)(nil),      // 3: vatz.plugin.ExecuteRequest
	(*ExecuteResponse)(nil),     // 4: vatz.plugin.ExecuteResponse
	(*CollectorVerifyInfo)(nil), // 5: vatz.plugin.CollectorVerifyInfo
	(*VerifyInfo)(nil),          // 6: vatz.plugin.VerifyInfo
	(*structpb.Struct)(nil),     // 7: google.protobuf.Struct
	(*emptypb.Empty)(nil),       // 8: google.protobuf.Empty
}
var file_proto_vatz_plugin_v1_plugin_proto_depIdxs = []int32{
	7, // 0: vatz.plugin.ExecuteRequest.execute_info:type_name -> google.protobuf.Struct
	7, // 1: vatz.plugin.ExecuteRequest.options:type_name -> google.protobuf.Struct
	1, // 2: vatz.plugin.ExecuteResponse.state:type_name -> vatz.plugin.STATE
	0, // 3: vatz.plugin.ExecuteResponse.alert_type:type_name -> vatz.plugin.ALERT_TYPE
	2, // 4: vatz.plugin.ExecuteResponse.severity:type_name -> vatz.plugin.SEVERITY
	7, // 5: vatz.plugin.CollectorVerifyInfo.options:type_name -> google.protobuf.Struct
	8, // 6: vatz.plugin.Plugin.verify:input_type -> google.protobuf.Empty
	3, // 7: vatz.plugin.Plugin.execute:input_type -> vatz.plugin.ExecuteRequest
	6, // 8: vatz.plugin.Plugin.verify:output_type -> vatz.plugin.VerifyInfo
	4, // 9: vatz.plugin.Plugin.execute:output_type -> vatz.plugin.ExecuteResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_vatz_plugin_v1_plugin_proto_init() }
func file_proto_vatz_plugin_v1_plugin_proto_init() {
	if File_proto_vatz_plugin_v1_plugin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_vatz_plugin_v1_plugin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vatz_plugin_v1_plugin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vatz_plugin_v1_plugin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectorVerifyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vatz_plugin_v1_plugin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_vatz_plugin_v1_plugin_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vatz_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_proto_vatz_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_proto_vatz_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_proto_vatz_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_proto_vatz_plugin_v1_plugin_proto = out.File
	file_proto_vatz_plugin_v1_plugin_proto_rawDesc = nil
	file_proto_vatz_plugin_v1_plugin_proto_goTypes = nil
	file_proto_vatz_plugin_v1_plugin_proto_depIdxs = nil
}
