// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: proto/vatz/manager/v2/endpoint.proto

package v2

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPluginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPluginRequest) Reset() {
	*x = ListPluginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vatz_manager_v2_endpoint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginRequest) ProtoMessage() {}

func (x *ListPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vatz_manager_v2_endpoint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginRequest.ProtoReflect.Descriptor instead.
func (*ListPluginRequest) Descriptor() ([]byte, []int) {
	return file_proto_vatz_manager_v2_endpoint_proto_rawDescGZIP(), []int{0}
}

type PluginMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PluginMetadata) Reset() {
	*x = PluginMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vatz_manager_v2_endpoint_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMetadata) ProtoMessage() {}

func (x *PluginMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vatz_manager_v2_endpoint_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMetadata.ProtoReflect.Descriptor instead.
func (*PluginMetadata) Descriptor() ([]byte, []int) {
	return file_proto_vatz_manager_v2_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *PluginMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListPluginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plugin []*PluginMetadata `protobuf:"bytes,1,rep,name=plugin,proto3" json:"plugin,omitempty"`
}

func (x *ListPluginResponse) Reset() {
	*x = ListPluginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vatz_manager_v2_endpoint_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginResponse) ProtoMessage() {}

func (x *ListPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vatz_manager_v2_endpoint_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginResponse.ProtoReflect.Descriptor instead.
func (*ListPluginResponse) Descriptor() ([]byte, []int) {
	return file_proto_vatz_manager_v2_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *ListPluginResponse) GetPlugin() []*PluginMetadata {
	if x != nil {
		return x.Plugin
	}
	return nil
}

type PluginMethod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Spec []*MethodFieldSpec `protobuf:"bytes,2,rep,name=spec,proto3" json:"spec,omitempty"`
}

func (x *PluginMethod) Reset() {
	*x = PluginMethod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vatz_manager_v2_endpoint_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMethod) ProtoMessage() {}

func (x *PluginMethod) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vatz_manager_v2_endpoint_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMethod.ProtoReflect.Descriptor instead.
func (*PluginMethod) Descriptor() ([]byte, []int) {
	return file_proto_vatz_manager_v2_endpoint_proto_rawDescGZIP(), []int{3}
}

func (x *PluginMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginMethod) GetSpec() []*MethodFieldSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// FIXME: Duplicated to handler's.
type MethodFieldSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *MethodFieldSpec) Reset() {
	*x = MethodFieldSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vatz_manager_v2_endpoint_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodFieldSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodFieldSpec) ProtoMessage() {}

func (x *MethodFieldSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vatz_manager_v2_endpoint_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodFieldSpec.ProtoReflect.Descriptor instead.
func (*MethodFieldSpec) Descriptor() ([]byte, []int) {
	return file_proto_vatz_manager_v2_endpoint_proto_rawDescGZIP(), []int{4}
}

func (x *MethodFieldSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MethodFieldSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DetailPluginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginName string `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
}

func (x *DetailPluginRequest) Reset() {
	*x = DetailPluginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vatz_manager_v2_endpoint_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailPluginRequest) ProtoMessage() {}

func (x *DetailPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vatz_manager_v2_endpoint_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailPluginRequest.ProtoReflect.Descriptor instead.
func (*DetailPluginRequest) Descriptor() ([]byte, []int) {
	return file_proto_vatz_manager_v2_endpoint_proto_rawDescGZIP(), []int{5}
}

func (x *DetailPluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

type DetailPluginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginName string          `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Methods    []*PluginMethod `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *DetailPluginResponse) Reset() {
	*x = DetailPluginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vatz_manager_v2_endpoint_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailPluginResponse) ProtoMessage() {}

func (x *DetailPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vatz_manager_v2_endpoint_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailPluginResponse.ProtoReflect.Descriptor instead.
func (*DetailPluginResponse) Descriptor() ([]byte, []int) {
	return file_proto_vatz_manager_v2_endpoint_proto_rawDescGZIP(), []int{6}
}

func (x *DetailPluginResponse) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *DetailPluginResponse) GetMethods() []*PluginMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

var File_proto_vatz_manager_v2_endpoint_proto protoreflect.FileDescriptor

var file_proto_vatz_manager_v2_endpoint_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x61, 0x74, 0x7a, 0x2f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x32, 0x2f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x76, 0x61, 0x74, 0x7a, 0x2e, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x24, 0x0a, 0x0e, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x4d, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x76, 0x61, 0x74, 0x7a, 0x2e, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x22,
	0x58, 0x0a, 0x0c, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x76, 0x61, 0x74, 0x7a, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x76, 0x32, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0x39, 0x0a, 0x0f, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x70, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x36, 0x0a, 0x13, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x70, 0x0a, 0x14,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x76, 0x61, 0x74, 0x7a, 0x2e, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x32, 0x88,
	0x02, 0x0a, 0x0f, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x6e, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x12, 0x22, 0x2e, 0x76, 0x61, 0x74, 0x7a, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x76, 0x32, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x76, 0x61, 0x74, 0x7a, 0x2e, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x11, 0x12, 0x0f, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x6c, 0x69,
	0x73, 0x74, 0x12, 0x84, 0x01, 0x0a, 0x0c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x12, 0x24, 0x2e, 0x76, 0x61, 0x74, 0x7a, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x76, 0x61, 0x74, 0x7a,
	0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x12, 0x1f, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2f, 0x7b, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x42, 0x0c, 0x5a, 0x0a, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_vatz_manager_v2_endpoint_proto_rawDescOnce sync.Once
	file_proto_vatz_manager_v2_endpoint_proto_rawDescData = file_proto_vatz_manager_v2_endpoint_proto_rawDesc
)

func file_proto_vatz_manager_v2_endpoint_proto_rawDescGZIP() []byte {
	file_proto_vatz_manager_v2_endpoint_proto_rawDescOnce.Do(func() {
		file_proto_vatz_manager_v2_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_vatz_manager_v2_endpoint_proto_rawDescData)
	})
	return file_proto_vatz_manager_v2_endpoint_proto_rawDescData
}

var file_proto_vatz_manager_v2_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_vatz_manager_v2_endpoint_proto_goTypes = []interface{}{
	(*ListPluginRequest)(nil),    // 0: vatz.manager.v2.ListPluginRequest
	(*PluginMetadata)(nil),       // 1: vatz.manager.v2.PluginMetadata
	(*ListPluginResponse)(nil),   // 2: vatz.manager.v2.ListPluginResponse
	(*PluginMethod)(nil),         // 3: vatz.manager.v2.PluginMethod
	(*MethodFieldSpec)(nil),      // 4: vatz.manager.v2.MethodFieldSpec
	(*DetailPluginRequest)(nil),  // 5: vatz.manager.v2.DetailPluginRequest
	(*DetailPluginResponse)(nil), // 6: vatz.manager.v2.DetailPluginResponse
}
var file_proto_vatz_manager_v2_endpoint_proto_depIdxs = []int32{
	1, // 0: vatz.manager.v2.ListPluginResponse.plugin:type_name -> vatz.manager.v2.PluginMetadata
	4, // 1: vatz.manager.v2.PluginMethod.spec:type_name -> vatz.manager.v2.MethodFieldSpec
	3, // 2: vatz.manager.v2.DetailPluginResponse.methods:type_name -> vatz.manager.v2.PluginMethod
	0, // 3: vatz.manager.v2.EndpointService.ListPlugin:input_type -> vatz.manager.v2.ListPluginRequest
	5, // 4: vatz.manager.v2.EndpointService.DetailPlugin:input_type -> vatz.manager.v2.DetailPluginRequest
	2, // 5: vatz.manager.v2.EndpointService.ListPlugin:output_type -> vatz.manager.v2.ListPluginResponse
	6, // 6: vatz.manager.v2.EndpointService.DetailPlugin:output_type -> vatz.manager.v2.DetailPluginResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_vatz_manager_v2_endpoint_proto_init() }
func file_proto_vatz_manager_v2_endpoint_proto_init() {
	if File_proto_vatz_manager_v2_endpoint_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_vatz_manager_v2_endpoint_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPluginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vatz_manager_v2_endpoint_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vatz_manager_v2_endpoint_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPluginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vatz_manager_v2_endpoint_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginMethod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vatz_manager_v2_endpoint_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodFieldSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vatz_manager_v2_endpoint_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetailPluginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vatz_manager_v2_endpoint_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetailPluginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_vatz_manager_v2_endpoint_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vatz_manager_v2_endpoint_proto_goTypes,
		DependencyIndexes: file_proto_vatz_manager_v2_endpoint_proto_depIdxs,
		MessageInfos:      file_proto_vatz_manager_v2_endpoint_proto_msgTypes,
	}.Build()
	File_proto_vatz_manager_v2_endpoint_proto = out.File
	file_proto_vatz_manager_v2_endpoint_proto_rawDesc = nil
	file_proto_vatz_manager_v2_endpoint_proto_goTypes = nil
	file_proto_vatz_manager_v2_endpoint_proto_depIdxs = nil
}
