// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: proto/vatz/manager/v2/handler.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RequestHandler_SendRequest_FullMethodName = "/vatz.manager.v2.RequestHandler/SendRequest"
)

// RequestHandlerClient is the client API for RequestHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RequestHandlerClient interface {
	SendRequest(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type requestHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewRequestHandlerClient(cc grpc.ClientConnInterface) RequestHandlerClient {
	return &requestHandlerClient{cc}
}

func (c *requestHandlerClient) SendRequest(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, RequestHandler_SendRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequestHandlerServer is the server API for RequestHandler service.
// All implementations must embed UnimplementedRequestHandlerServer
// for forward compatibility
type RequestHandlerServer interface {
	SendRequest(context.Context, *UserRequest) (*UserResponse, error)
	mustEmbedUnimplementedRequestHandlerServer()
}

// UnimplementedRequestHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedRequestHandlerServer struct {
}

func (UnimplementedRequestHandlerServer) SendRequest(context.Context, *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequest not implemented")
}
func (UnimplementedRequestHandlerServer) mustEmbedUnimplementedRequestHandlerServer() {}

// UnsafeRequestHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RequestHandlerServer will
// result in compilation errors.
type UnsafeRequestHandlerServer interface {
	mustEmbedUnimplementedRequestHandlerServer()
}

func RegisterRequestHandlerServer(s grpc.ServiceRegistrar, srv RequestHandlerServer) {
	s.RegisterService(&RequestHandler_ServiceDesc, srv)
}

func _RequestHandler_SendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestHandlerServer).SendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestHandler_SendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestHandlerServer).SendRequest(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RequestHandler_ServiceDesc is the grpc.ServiceDesc for RequestHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RequestHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vatz.manager.v2.RequestHandler",
	HandlerType: (*RequestHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRequest",
			Handler:    _RequestHandler_SendRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/vatz/manager/v2/handler.proto",
}
