name: Vatz Poro-buffer auto compile

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'proto/vatz/**/**/**'
jobs:
  autogen:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.VATZ_PROTO_ACTION_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Install Protobuf Generator
        run: |
          PROTOC_ZIP=protoc-3.14.0-linux-x86_64.zip
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/$PROTOC_ZIP
          sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
          sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
          sudo ln -sfn /usr/local/bin/protoc /usr/bin/protoc
          curl -OL https://github.com/protocolbuffers/protobuf-go/releases/download/v1.27.1/protoc-gen-go.v1.27.1.linux.amd64.tar.gz
          tar -xvf protoc-gen-go.v1.27.1.linux.amd64.tar.gz
          sudo mv protoc-gen-go /usr/bin/protoc-gen-go
          curl -OL https://github.com/jsirianni/grpc-go/releases/download/v1.39.1-js/protoc-gen-go-grpc
          sudo chmod +x protoc-gen-go-grpc && sudo mv protoc-gen-go-grpc /usr/bin/protoc-gen-go-grpc
      - name: clean previous-protos
        run: |
          make clean
          rm -rf protoc-gen-go.v1.27.1.linux.amd64.tar.gz protoc-3.14.0-linux-x86_64.zip
      - name: Install Protoc
        run: |
          git submodule init
          git submodule update
          make compile
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'compile and update with compiled pb.go(s)'
          add: '*'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force: true
